//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace OrmBattle.EFModel
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PerformanceTestEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PerformanceTestEntities object using the connection string found in the 'PerformanceTestEntities' section of the application configuration file.
        /// </summary>
        public PerformanceTestEntities() : base("name=PerformanceTestEntities", "PerformanceTestEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PerformanceTestEntities object.
        /// </summary>
        public PerformanceTestEntities(string connectionString) : base(connectionString, "PerformanceTestEntities")
        {
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PerformanceTestEntities object.
        /// </summary>
        public PerformanceTestEntities(EntityConnection connection) : base(connection, "PerformanceTestEntities")
        {
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Simplest> Simplests
        {
            get
            {
                if ((_Simplests == null))
                {
                    _Simplests = base.CreateObjectSet<Simplest>("Simplests");
                }
                return _Simplests;
            }
        }
        private ObjectSet<Simplest> _Simplests;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Simplests EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSimplests(Simplest simplest)
        {
            base.AddObject("Simplests", simplest);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PerformanceTestModel", Name="Simplest")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Simplest : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Simplest object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="value">Initial value of the Value property.</param>
        public static Simplest CreateSimplest(global::System.Int64 id, global::System.Int64 value)
        {
            Simplest simplest = new Simplest();
            simplest.Id = id;
            simplest.Value = value;
            return simplest;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.Int64 _Value;
        partial void OnValueChanging(global::System.Int64 value);
        partial void OnValueChanged();

        #endregion
    
    }

    #endregion
    
}
