#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using OrmBattle.TelerikModel.PerformanceTest;
using Telerik.OpenAccess.Metadata;


namespace OrmBattle.TelerikModel.PerformanceTest	
{	
	public partial class PerformanceTest : OpenAccessContext
	{
		private static string connectionStringName = "PerformanceTest";
			
		private static BackendConfiguration backend = GetBackendConfiguration();
		
			
		private static MetadataSource metadataSource = XmlMetadataSource.FromAssemblyResource("PerformanceTest.rlinq");
	
		public PerformanceTest()
			:base(connectionStringName, backend, metadataSource)
		{ }
		
		public PerformanceTest(string connection)
			:base(connection, backend, metadataSource)
		{ }
	
		public PerformanceTest(BackendConfiguration backendConfiguration)
			:base(connectionStringName, backendConfiguration, metadataSource)
		{ }
			
		public PerformanceTest(string connection, MetadataSource metadataSource)
			:base(connection, backend, metadataSource)
		{ }
		
		public PerformanceTest(string connection, BackendConfiguration backendConfiguration, MetadataSource metadataSource)
			:base(connection, backendConfiguration, metadataSource)
		{ }
			
		public IQueryable<Simplest> Simplests 
		{
	    	get
	    	{
	        	return this.GetAll<Simplest>();
	    	}
		}
		
		public static BackendConfiguration GetBackendConfiguration()
		{
			BackendConfiguration backend = new BackendConfiguration();
			backend.Backend = "mssql";
			return backend;
		}

    public IObjectScope Scope
    {
      get
      {
        return this.GetScope();
      }
    }
	}
}
#pragma warning restore 1591
