

using System;
using System.Collections.Generic;

namespace OrmBattle.TelerikModel.PerformanceTest
{
  // Generated by Telerik OpenAccess
  // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
  [Telerik.OpenAccess.Persistent(IdentityField = "id")]
  public partial class Simplest
  {
    private long id; // pk 

    private long value;





  }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace OrmBattle.TelerikModel.PerformanceTest 
{
    //Generated by Telerik OpenAccess
    public partial class Simplest 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public Simplest() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("id")]
        public long Id
        {
            get { return id; }
            set { this.id = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("value")]
        public long Value
        {
            get { return value; }
            set { this.value = value; }
        }
 

    }
}
*/
#endregion //main class file contents
