//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Xml.Serialization;

namespace OrmBattle.NHibernateModel.Northwind
{
	[Serializable]
	[XmlInclude(typeof(OrderDetail))]
	[SoapInclude(typeof(OrderDetail))]
	public class AbstractOrder
	{
		public virtual int Id { get; set; }

		public virtual Decimal Freight { get; set; }

		[SoapElement(IsNullable = true)]
		public virtual DateTime? OrderDate { get; set; }

		[SoapElement(IsNullable = true)]
		public virtual DateTime? RequiredDate { get; set; }

		public virtual string ShipAddress { get; set; }

		public virtual string ShipCity { get; set; }

		public virtual string ShipCountry { get; set; }

		public virtual string ShipName { get; set; }

		[SoapElement(IsNullable = true)]
		public virtual DateTime? ShippedDate { get; set; }

		public virtual string ShipPostalCode { get; set; }

		public virtual string ShipRegion { get; set; }

		public virtual Customer Customer { get; set; }

		public virtual Employee Employee { get; set; }

		public virtual IList<OrderDetail> OrderDetails { get; set; }

		public virtual Shipper Shipper { get; set; }
	}

	[Serializable]
	public class Order : AbstractOrder
	{
	}
}