//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace OrmBattle.NHibernateModel.Northwind
{
	[Serializable]
	public class AbstractOrderDetail
	{
    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }

		public virtual float Discount { get; set; }

		public virtual short Quantity { get; set; }

		public virtual decimal UnitPrice { get; set; }

	  public virtual bool Equals(AbstractOrderDetail other)
	  {
	    if (ReferenceEquals(null, other)) return false;
	    if (ReferenceEquals(this, other)) return true;
	    return Equals(other.Order, Order) && Equals(other.Product, Product);
	  }

	  public override bool Equals(object obj)
	  {
	    if (ReferenceEquals(null, obj)) return false;
	    if (ReferenceEquals(this, obj)) return true;
	    if (obj.GetType() != typeof (AbstractOrderDetail)) return false;
	    return Equals((AbstractOrderDetail) obj);
	  }

	  public override int GetHashCode()
	  {
	    unchecked {
	      return ((Order != null ? Order.GetHashCode() : 0)*397) ^ (Product != null ? Product.GetHashCode() : 0);
	    }
	  }
	}

	[Serializable]
	public class OrderDetail : AbstractOrderDetail
	{
	}
}