using System;
using System.Collections.Generic;

namespace OrmBattle.TelerikModel.Northwind
{
  // Generated by Telerik OpenAccess
  // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialuserdefault.vm
  // NOTE: Field declarations and 'Object ID' class implementation are added to the 'designer' file.
  //       Changes made to the 'designer' file will be overwritten by the wizard.  	
  public partial class OrderDetail
  {
    //The 'no-args' constructor required by OpenAccess. 
    public OrderDetail()
    {
    }

    [Telerik.OpenAccess.FieldAlias("orderId")]
    public int OrderId
    {
      get { return orderId; }
      set { this.orderId = value; }
    }

    [Telerik.OpenAccess.FieldAlias("productId")]
    public int ProductId
    {
      get { return productId; }
      set { this.productId = value; }
    }

    [Telerik.OpenAccess.FieldAlias("discount")]
    public float Discount
    {
      get { return discount; }
      set { this.discount = value; }
    }

    [Telerik.OpenAccess.FieldAlias("quantity")]
    public short Quantity
    {
      get { return quantity; }
      set { this.quantity = value; }
    }

    [Telerik.OpenAccess.FieldAlias("unitPrice")]
    public Decimal UnitPrice
    {
      get { return unitPrice; }
      set { this.unitPrice = value; }
    }

    [Telerik.OpenAccess.FieldAlias("order")]
    public Order Order
    {
      get { return order; }
      set { this.order = value; }
    }

    [Telerik.OpenAccess.FieldAlias("product")]
    public Product Product
    {
      get { return product; }
      set { this.product = value; }
    }


  }
}
