

using System;
using System.Collections.Generic;

namespace OrmBattle.TelerikModel.Northwind
{
  // Generated by Telerik OpenAccess
  // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
  [Telerik.OpenAccess.Persistent(IdentityField = "id")]
  public partial class Product
  {
    private int id; // pk 

    private bool discontinued;

    private string productName;

    private string quantityPerUnit;

    private short? reorderLevel;

    private Decimal? unitPrice;

    private short? unitsInStock;

    private short? unitsOnOrder;

    private Category category; // inverse Category.products

    private Supplier supplier; // inverse Supplier.products





  }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace OrmBattle.TelerikModel.Northwind 
{
    //Generated by Telerik OpenAccess
    public partial class Product 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public Product() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("id")]
        public int Id
        {
            get { return id; }
            set { this.id = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("discontinued")]
        public bool Discontinued
        {
            get { return discontinued; }
            set { this.discontinued = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("productName")]
        public string ProductName
        {
            get { return productName; }
            set { this.productName = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("quantityPerUnit")]
        public string QuantityPerUnit
        {
            get { return quantityPerUnit; }
            set { this.quantityPerUnit = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("reorderLevel")]
        public short? ReorderLevel
        {
            get { return reorderLevel; }
            set { this.reorderLevel = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("unitPrice")]
        public Decimal? UnitPrice
        {
            get { return unitPrice; }
            set { this.unitPrice = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("unitsInStock")]
        public short? UnitsInStock
        {
            get { return unitsInStock; }
            set { this.unitsInStock = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("unitsOnOrder")]
        public short? UnitsOnOrder
        {
            get { return unitsOnOrder; }
            set { this.unitsOnOrder = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("category")]
        public Category Category
        {
            get { return category; }
            set { this.category = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("supplier")]
        public Supplier Supplier
        {
            get { return supplier; }
            set { this.supplier = value; }
        }
 

    }
}
*/
#endregion //main class file contents
