using System;
using System.Collections.Generic;

namespace OrmBattle.TelerikModel.Northwind
{
  // Generated by Telerik OpenAccess
  // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialuserdefault.vm
  // NOTE: Field declarations and 'Object ID' class implementation are added to the 'designer' file.
  //       Changes made to the 'designer' file will be overwritten by the wizard.  	
  public partial class Territory
  {
    //The 'no-args' constructor required by OpenAccess. 
    public Territory()
    {
    }

    [Telerik.OpenAccess.FieldAlias("id")]
    public string Id
    {
      get { return id; }
      set { this.id = value; }
    }

    [Telerik.OpenAccess.FieldAlias("territoryDescription")]
    public string TerritoryDescription
    {
      get { return territoryDescription; }
      set { this.territoryDescription = value; }
    }

    [Telerik.OpenAccess.FieldAlias("region")]
    public Region Region
    {
      get { return region; }
      set { this.region = value; }
    }

    [Telerik.OpenAccess.FieldAlias("employees")]
    public IList<Employee> Employees
    {
      get { return employees; }
    }


  }
}
