

using System;
using System.Collections.Generic;

namespace OrmBattle.TelerikModel.Northwind
{
  // Generated by Telerik OpenAccess
  // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
  [Telerik.OpenAccess.Persistent(IdentityField = "id")]
  public partial class Territory
  {
    private string id; // pk 

    private string territoryDescription;

    private Region region; // inverse Region.territories

    private IList<Employee> employees = new List<Employee>();  // inverse Employee.territories





  }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace OrmBattle.TelerikModel.Northwind 
{
    //Generated by Telerik OpenAccess
    public partial class Territory 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public Territory() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("id")]
        public string Id
        {
            get { return id; }
            set { this.id = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("territoryDescription")]
        public string TerritoryDescription
        {
            get { return territoryDescription; }
            set { this.territoryDescription = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("region")]
        public Region Region
        {
            get { return region; }
            set { this.region = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("employees")]
        public IList<Employee> Employees
        {
            get { return employees; }
        }
 

    }
}
*/
#endregion //main class file contents
