#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;


namespace OrmBattle.TelerikModel.Northwind	
{
	public partial class Category
	{
		private int categoryID;
		public virtual int Id 
		{ 
		    get
		    {
		        return this.categoryID;
		    }
		    set
		    {
		        this.categoryID = value;
		    }
		}
		
		private string categoryName;
		public virtual string CategoryName 
		{ 
		    get
		    {
		        return this.categoryName;
		    }
		    set
		    {
		        this.categoryName = value;
		    }
		}
		
		private string description;
		public virtual string Description 
		{ 
		    get
		    {
		        return this.description;
		    }
		    set
		    {
		        this.description = value;
		    }
		}
		
		private byte[] picture;
		public virtual byte[] Picture 
		{ 
		    get
		    {
		        return this.picture;
		    }
		    set
		    {
		        this.picture = value;
		    }
		}
		
		private IList<Product> products = new List<Product>();
		public virtual IList<Product> Products 
		{ 
		    get
		    {
		        return this.products;
		    }
		}
		
	}
}
