#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;


namespace OrmBattle.TelerikModel.Northwind	
{
	public partial class Customer
	{
		private string customerID;
		public virtual string Id 
		{ 
		    get
		    {
		        return this.customerID;
		    }
		    set
		    {
		        this.customerID = value;
		    }
		}
		
		private string companyName;
		public virtual string CompanyName 
		{ 
		    get
		    {
		        return this.companyName;
		    }
		    set
		    {
		        this.companyName = value;
		    }
		}
		
		private string contactName;
		public virtual string ContactName 
		{ 
		    get
		    {
		        return this.contactName;
		    }
		    set
		    {
		        this.contactName = value;
		    }
		}
		
		private string contactTitle;
		public virtual string ContactTitle 
		{ 
		    get
		    {
		        return this.contactTitle;
		    }
		    set
		    {
		        this.contactTitle = value;
		    }
		}
		
		private string address;
		public virtual string Address 
		{ 
		    get
		    {
		        return this.address;
		    }
		    set
		    {
		        this.address = value;
		    }
		}
		
		private string city;
		public virtual string City 
		{ 
		    get
		    {
		        return this.city;
		    }
		    set
		    {
		        this.city = value;
		    }
		}
		
		private string region;
		public virtual string Region 
		{ 
		    get
		    {
		        return this.region;
		    }
		    set
		    {
		        this.region = value;
		    }
		}
		
		private string postalCode;
		public virtual string PostalCode 
		{ 
		    get
		    {
		        return this.postalCode;
		    }
		    set
		    {
		        this.postalCode = value;
		    }
		}
		
		private string country;
		public virtual string Country 
		{ 
		    get
		    {
		        return this.country;
		    }
		    set
		    {
		        this.country = value;
		    }
		}
		
		private string phone;
		public virtual string Phone 
		{ 
		    get
		    {
		        return this.phone;
		    }
		    set
		    {
		        this.phone = value;
		    }
		}
		
		private string fax;
		public virtual string Fax 
		{ 
		    get
		    {
		        return this.fax;
		    }
		    set
		    {
		        this.fax = value;
		    }
		}
		
		private IList<Order> orders = new List<Order>();
		public virtual IList<Order> Orders 
		{ 
		    get
		    {
		        return this.orders;
		    }
		}
		
	}
}
