#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;


namespace OrmBattle.TelerikModel.Northwind	
{
	public partial class Employee
	{
		private int employeeID;
		public virtual int Id 
		{ 
		    get
		    {
		        return this.employeeID;
		    }
		    set
		    {
		        this.employeeID = value;
		    }
		}
		
		private string lastName;
		public virtual string LastName 
		{ 
		    get
		    {
		        return this.lastName;
		    }
		    set
		    {
		        this.lastName = value;
		    }
		}
		
		private string firstName;
		public virtual string FirstName 
		{ 
		    get
		    {
		        return this.firstName;
		    }
		    set
		    {
		        this.firstName = value;
		    }
		}
		
		private string title;
		public virtual string Title 
		{ 
		    get
		    {
		        return this.title;
		    }
		    set
		    {
		        this.title = value;
		    }
		}
		
		private string titleOfCourtesy;
		public virtual string TitleOfCourtesy 
		{ 
		    get
		    {
		        return this.titleOfCourtesy;
		    }
		    set
		    {
		        this.titleOfCourtesy = value;
		    }
		}
		
		private DateTime? birthDate;
		public virtual DateTime? BirthDate 
		{ 
		    get
		    {
		        return this.birthDate;
		    }
		    set
		    {
		        this.birthDate = value;
		    }
		}
		
		private DateTime? hireDate;
		public virtual DateTime? HireDate 
		{ 
		    get
		    {
		        return this.hireDate;
		    }
		    set
		    {
		        this.hireDate = value;
		    }
		}
		
		private string address;
		public virtual string Address 
		{ 
		    get
		    {
		        return this.address;
		    }
		    set
		    {
		        this.address = value;
		    }
		}
		
		private string city;
		public virtual string City 
		{ 
		    get
		    {
		        return this.city;
		    }
		    set
		    {
		        this.city = value;
		    }
		}
		
		private string region;
		public virtual string Region 
		{ 
		    get
		    {
		        return this.region;
		    }
		    set
		    {
		        this.region = value;
		    }
		}
		
		private string postalCode;
		public virtual string PostalCode 
		{ 
		    get
		    {
		        return this.postalCode;
		    }
		    set
		    {
		        this.postalCode = value;
		    }
		}
		
		private string country;
		public virtual string Country 
		{ 
		    get
		    {
		        return this.country;
		    }
		    set
		    {
		        this.country = value;
		    }
		}
		
		private string homePhone;
		public virtual string HomePhone 
		{ 
		    get
		    {
		        return this.homePhone;
		    }
		    set
		    {
		        this.homePhone = value;
		    }
		}
		
		private string extension;
		public virtual string Extension 
		{ 
		    get
		    {
		        return this.extension;
		    }
		    set
		    {
		        this.extension = value;
		    }
		}
		
		private byte[] photo;
		public virtual byte[] Photo 
		{ 
		    get
		    {
		        return this.photo;
		    }
		    set
		    {
		        this.photo = value;
		    }
		}
		
		private string notes;
		public virtual string Notes 
		{ 
		    get
		    {
		        return this.notes;
		    }
		    set
		    {
		        this.notes = value;
		    }
		}
		
		private int? reportsToID;
		public virtual int? ReportsToID 
		{ 
		    get
		    {
		        return this.reportsToID;
		    }
		    set
		    {
		        this.reportsToID = value;
		    }
		}
		
		private string photoPath;
		public virtual string PhotoPath 
		{ 
		    get
		    {
		        return this.photoPath;
		    }
		    set
		    {
		        this.photoPath = value;
		    }
		}
		
		private Employee reportsTo;
		public virtual Employee ReportsTo 
		{ 
		    get
		    {
		        return this.reportsTo;
		    }
		    set
		    {
		        this.reportsTo = value;
		    }
		}
		
		private IList<Territory> territories = new List<Territory>();
		public virtual IList<Territory> Territories 
		{ 
		    get
		    {
		        return this.territories;
		    }
		}
		
		private IList<Employee> employees = new List<Employee>();
		public virtual IList<Employee> Employees 
		{ 
		    get
		    {
		        return this.employees;
		    }
		}
		
		private IList<Order> orders = new List<Order>();
		public virtual IList<Order> Orders 
		{ 
		    get
		    {
		        return this.orders;
		    }
		}
		
	}
}
