

using System;
using System.Collections.Generic;

namespace OrmBattle.TelerikModel.Northwind
{
  // Generated by Telerik OpenAccess
  // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
  [Telerik.OpenAccess.Persistent(IdentityField = "id")]
  public partial class Order
  {
    private int id; // pk 

    private Decimal freight;

    private DateTime? orderDate;

    private DateTime? requiredDate;

    private string shipAddress;

    private string shipCity;

    private string shipCountry;

    private string shipName;

    private string shipPostalCode;

    private string shipRegion;

    private DateTime? shippedDate;

    private Customer customer; // inverse Customer.orders

    private Employee employee;

    private Shipper shipper; // inverse Shipper.orders

    private IList<OrderDetail> orderDetails = new List<OrderDetail>();  // inverse OrderDetail.order





  }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace OrmBattle.TelerikModel.Northwind 
{
    //Generated by Telerik OpenAccess
    public partial class Order 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public Order() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("orderId")]
        public int OrderId
        {
            get { return orderId; }
            set { this.orderId = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("freight")]
        public Decimal Freight
        {
            get { return freight; }
            set { this.freight = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("orderDate")]
        public DateTime? OrderDate
        {
            get { return orderDate; }
            set { this.orderDate = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("requiredDate")]
        public DateTime? RequiredDate
        {
            get { return requiredDate; }
            set { this.requiredDate = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("shipAddress")]
        public string ShipAddress
        {
            get { return shipAddress; }
            set { this.shipAddress = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("shipCity")]
        public string ShipCity
        {
            get { return shipCity; }
            set { this.shipCity = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("shipCountry")]
        public string ShipCountry
        {
            get { return shipCountry; }
            set { this.shipCountry = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("shipName")]
        public string ShipName
        {
            get { return shipName; }
            set { this.shipName = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("shipPostalCode")]
        public string ShipPostalCode
        {
            get { return shipPostalCode; }
            set { this.shipPostalCode = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("shipRegion")]
        public string ShipRegion
        {
            get { return shipRegion; }
            set { this.shipRegion = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("shippedDate")]
        public DateTime? ShippedDate
        {
            get { return shippedDate; }
            set { this.shippedDate = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("customer")]
        public Customer Customer
        {
            get { return customer; }
            set { this.customer = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("employee")]
        public Employee Employee
        {
            get { return employee; }
            set { this.employee = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("shipper")]
        public Shipper Shipper
        {
            get { return shipper; }
            set { this.shipper = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("orderDetails")]
        public IList<OrderDetail> OrderDetails
        {
            get { return orderDetails; }
        }
 

    }
}
*/
#endregion //main class file contents
