#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;


namespace OrmBattle.TelerikModel.Northwind	
{
	public partial class OrderDetail
	{
		private int orderID;
		public virtual int OrderID 
		{ 
		    get
		    {
		        return this.orderID;
		    }
		    set
		    {
		        this.orderID = value;
		    }
		}
		
		private int productID;
		public virtual int ProductID 
		{ 
		    get
		    {
		        return this.productID;
		    }
		    set
		    {
		        this.productID = value;
		    }
		}
		
		private decimal unitPrice;
		public virtual decimal UnitPrice 
		{ 
		    get
		    {
		        return this.unitPrice;
		    }
		    set
		    {
		        this.unitPrice = value;
		    }
		}
		
		private short quantity;
		public virtual short Quantity 
		{ 
		    get
		    {
		        return this.quantity;
		    }
		    set
		    {
		        this.quantity = value;
		    }
		}
		
		private float discount;
		public virtual float Discount 
		{ 
		    get
		    {
		        return this.discount;
		    }
		    set
		    {
		        this.discount = value;
		    }
		}
		
		private Order order;
		public virtual Order Order 
		{ 
		    get
		    {
		        return this.order;
		    }
		    set
		    {
		        this.order = value;
		    }
		}
		
		private Product product;
		public virtual Product Product 
		{ 
		    get
		    {
		        return this.product;
		    }
		    set
		    {
		        this.product = value;
		    }
		}
		
		public class ID : Telerik.OpenAccess.IObjectId
	    {
			public int orderID; //pk
			public int productID; //pk
	
			public ID()
			{ }
				
			public ID(string s)
			{
				int i, p = 0;
				i = s.IndexOf('-', p);
				orderID = Int32.Parse(s.Substring(p, i - p));
				p = i + 1;
				i = s.IndexOf('-', p);
				productID = Int32.Parse(s.Substring(p));
			}
	
			public override bool Equals(object o)
			{
				if (this == o) return true;
				
				if(!(o is OrderDetail.ID)) return false;
				
				OrderDetail.ID id = (OrderDetail.ID)o;
	
				if(this.orderID != id.orderID) return false;
	
				if(this.productID != id.productID) return false;
				return true;
			}
			
			public override int GetHashCode()
			{
	            int result = 0;
				
				result = 29 *result + orderID.GetHashCode();
				
				result = 29 *result + productID.GetHashCode();
				return result;
			}
			
		public override string ToString()
		{
			System.Text.StringBuilder buffer = new System.Text.StringBuilder();
				
				buffer.Append(orderID).Append('-');
				
				buffer.Append(productID);
			return buffer.ToString();
		}
	}
	}
}
