using System;
using System.Collections.Generic;

namespace OrmBattle.TelerikModel.Northwind
{
  // Generated by Telerik OpenAccess
  // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialuserdefault.vm
  // NOTE: Field declarations and 'Object ID' class implementation are added to the 'designer' file.
  //       Changes made to the 'designer' file will be overwritten by the wizard.  	
  public partial class Order
  {
    //The 'no-args' constructor required by OpenAccess. 
    public Order()
    {
    }

    [Telerik.OpenAccess.FieldAlias("id")]
    public int Id
    {
      get { return id; }
      set { this.id = value; }
    }

    [Telerik.OpenAccess.FieldAlias("freight")]
    public Decimal Freight
    {
      get { return freight; }
      set { this.freight = value; }
    }

    [Telerik.OpenAccess.FieldAlias("orderDate")]
    public DateTime? OrderDate
    {
      get { return orderDate; }
      set { this.orderDate = value; }
    }

    [Telerik.OpenAccess.FieldAlias("requiredDate")]
    public DateTime? RequiredDate
    {
      get { return requiredDate; }
      set { this.requiredDate = value; }
    }

    [Telerik.OpenAccess.FieldAlias("shipAddress")]
    public string ShipAddress
    {
      get { return shipAddress; }
      set { this.shipAddress = value; }
    }

    [Telerik.OpenAccess.FieldAlias("shipCity")]
    public string ShipCity
    {
      get { return shipCity; }
      set { this.shipCity = value; }
    }

    [Telerik.OpenAccess.FieldAlias("shipCountry")]
    public string ShipCountry
    {
      get { return shipCountry; }
      set { this.shipCountry = value; }
    }

    [Telerik.OpenAccess.FieldAlias("shipName")]
    public string ShipName
    {
      get { return shipName; }
      set { this.shipName = value; }
    }

    [Telerik.OpenAccess.FieldAlias("shipPostalCode")]
    public string ShipPostalCode
    {
      get { return shipPostalCode; }
      set { this.shipPostalCode = value; }
    }

    [Telerik.OpenAccess.FieldAlias("shipRegion")]
    public string ShipRegion
    {
      get { return shipRegion; }
      set { this.shipRegion = value; }
    }

    [Telerik.OpenAccess.FieldAlias("shippedDate")]
    public DateTime? ShippedDate
    {
      get { return shippedDate; }
      set { this.shippedDate = value; }
    }

    [Telerik.OpenAccess.FieldAlias("customer")]
    public Customer Customer
    {
      get { return customer; }
      set { this.customer = value; }
    }

    [Telerik.OpenAccess.FieldAlias("employee")]
    public Employee Employee
    {
      get { return employee; }
      set { this.employee = value; }
    }

    [Telerik.OpenAccess.FieldAlias("shipper")]
    public Shipper Shipper
    {
      get { return shipper; }
      set { this.shipper = value; }
    }

    [Telerik.OpenAccess.FieldAlias("orderDetails")]
    public IList<OrderDetail> OrderDetails
    {
      get { return orderDetails; }
    }


  }
}
