using System;
using System.Collections.Generic;

namespace OrmBattle.TelerikModel.Northwind
{
  // Generated by Telerik OpenAccess
  // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialuserdefault.vm
  // NOTE: Field declarations and 'Object ID' class implementation are added to the 'designer' file.
  //       Changes made to the 'designer' file will be overwritten by the wizard.  	
  public partial class Region
  {
    //The 'no-args' constructor required by OpenAccess. 
    public Region()
    {
    }

    [Telerik.OpenAccess.FieldAlias("id")]
    public int Id
    {
      get { return id; }
      set { this.id = value; }
    }

    [Telerik.OpenAccess.FieldAlias("regionDescription")]
    public string RegionDescription
    {
      get { return regionDescription; }
      set { this.regionDescription = value; }
    }

    [Telerik.OpenAccess.FieldAlias("territories")]
    public IList<Territory> Territories
    {
      get { return territories; }
    }


  }
}
