#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;


namespace OrmBattle.TelerikModel.Northwind	
{
	public partial class Region
	{
		private int regionID;
		public virtual int Id 
		{ 
		    get
		    {
		        return this.regionID;
		    }
		    set
		    {
		        this.regionID = value;
		    }
		}
		
		private string regionDescription;
		public virtual string RegionDescription 
		{ 
		    get
		    {
		        return this.regionDescription;
		    }
		    set
		    {
		        this.regionDescription = value;
		    }
		}
		
		private IList<Territory> territories = new List<Territory>();
		public virtual IList<Territory> Territories 
		{ 
		    get
		    {
		        return this.territories;
		    }
		}
		
	}
}
