using System;
using System.Collections.Generic;

namespace OrmBattle.TelerikModel.Northwind
{
  // Generated by Telerik OpenAccess
  // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialuserdefault.vm
  // NOTE: Field declarations and 'Object ID' class implementation are added to the 'designer' file.
  //       Changes made to the 'designer' file will be overwritten by the wizard.  	
  public partial class Shipper
  {
    //The 'no-args' constructor required by OpenAccess. 
    public Shipper()
    {
    }

    [Telerik.OpenAccess.FieldAlias("id")]
    public int Id
    {
      get { return id; }
      set { this.id = value; }
    }

    [Telerik.OpenAccess.FieldAlias("companyName")]
    public string CompanyName
    {
      get { return companyName; }
      set { this.companyName = value; }
    }

    [Telerik.OpenAccess.FieldAlias("phone")]
    public string Phone
    {
      get { return phone; }
      set { this.phone = value; }
    }

    [Telerik.OpenAccess.FieldAlias("orders")]
    public IList<Order> Orders
    {
      get { return orders; }
    }


  }
}
