#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;


namespace OrmBattle.TelerikModel.Northwind	
{
	public partial class Shipper
	{
		private int shipperID;
		public virtual int Id 
		{ 
		    get
		    {
		        return this.shipperID;
		    }
		    set
		    {
		        this.shipperID = value;
		    }
		}
		
		private string companyName;
		public virtual string CompanyName 
		{ 
		    get
		    {
		        return this.companyName;
		    }
		    set
		    {
		        this.companyName = value;
		    }
		}
		
		private string phone;
		public virtual string Phone 
		{ 
		    get
		    {
		        return this.phone;
		    }
		    set
		    {
		        this.phone = value;
		    }
		}
		
		private IList<Order> orders = new List<Order>();
		public virtual IList<Order> Orders 
		{ 
		    get
		    {
		        return this.orders;
		    }
		}
		
	}
}
