

using System;
using System.Collections.Generic;

namespace OrmBattle.TelerikModel.Northwind
{
  // Generated by Telerik OpenAccess
  // Used template: c:\program files\telerik\openaccess orm\sdk\IDEIntegrations\templates\PCClassGeneration\cs\templates\classgen\class\partialdesignerdefault.vm
  [Telerik.OpenAccess.Persistent(IdentityField = "id")]
  public partial class Shipper
  {
    private int id; // pk 

    private string companyName;

    private string phone;

    private IList<Order> orders = new List<Order>();  // inverse Order.shipper





  }
}

#region main class file contents
/*


using System;
using System.Collections.Generic;

namespace OrmBattle.TelerikModel.Northwind 
{
    //Generated by Telerik OpenAccess
    public partial class Shipper 
    {
        //The 'no-args' constructor required by OpenAccess. 
        public Shipper() 
        {
        }
    
        [Telerik.OpenAccess.FieldAlias("id")]
        public int Id
        {
            get { return id; }
            set { this.id = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("companyName")]
        public string CompanyName
        {
            get { return companyName; }
            set { this.companyName = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("phone")]
        public string Phone
        {
            get { return phone; }
            set { this.phone = value; }
        }
 
        [Telerik.OpenAccess.FieldAlias("orders")]
        public IList<Order> Orders
        {
            get { return orders; }
        }
 

    }
}
*/
#endregion //main class file contents
