#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;


namespace OrmBattle.TelerikModel.Northwind	
{
	public partial class Territory
	{
		private string territoryID;
		public virtual string Id 
		{ 
		    get
		    {
		        return this.territoryID;
		    }
		    set
		    {
		        this.territoryID = value;
		    }
		}
		
		private string territoryDescription;
		public virtual string TerritoryDescription 
		{ 
		    get
		    {
		        return this.territoryDescription;
		    }
		    set
		    {
		        this.territoryDescription = value;
		    }
		}
		
		private int regionID;
		public virtual int RegionID 
		{ 
		    get
		    {
		        return this.regionID;
		    }
		    set
		    {
		        this.regionID = value;
		    }
		}
		
		private Region region;
		public virtual Region Region 
		{ 
		    get
		    {
		        return this.region;
		    }
		    set
		    {
		        this.region = value;
		    }
		}
		
		private IList<Employee> employees = new List<Employee>();
		public virtual IList<Employee> Employees 
		{ 
		    get
		    {
		        return this.employees;
		    }
		}
		
	}
}
